### ISSUE TITLE
Bug with popext on mem addresses

### ISSUE THREAD

**Issue by MuckerMayhem** [Babakanoosh/Visual-SSBC#5]
Popext on memory addresses (ex 0100 or 0200) causes the stack pointer to decrement with every step after executing popext until it hits -1 and it flatlines.

sigma5r seems to demonstrate this bug from what I found.

https://i.gyazo.com/94f6a68fb8f1f44b422e8d5a5797d38f.png What I get when running with sigma5r.

**Comment by Babakanoosh** [comment]
Known issue with Julie Beeston's code. Code space is 0-255. Line 0x27 of sigma5r is attempting to pop a value to 256 when 255 is the maximum. Reducing the popext to 255 or less exposes another bug ("NaN"). 

I'm working on a new version of the interpreter that will resolve these issues in the alpha branch. The interpreter code does not work with it yet. New version may be up in 2-3 days.
